-- Datos de prueba generados a partir de data/ciudades.csv, data/personajes.csv y data/hechos.csv.
-- Ejecutar despues de schema.sql. Sustituye por completo al seed.sql anterior (3 personajes).
--
-- Ya se habia cargado antes el seed de 3 personajes en este proyecto, asi que hace falta
-- vaciar las tablas primero para no duplicar filas. OJO: esto borra tambien el historial
-- de partidas jugadas hasta ahora (tablas partidas/respuestas_partida).
truncate table hechos, partidas, respuestas_partida, personajes, ciudades restart identity cascade;

insert into ciudades (nombre, lat, lon) values
('Actium', 38.9500, 20.7500),
('Aracataca', 10.5919, -74.1864),
('Génova', 44.4056, 8.9463),
('Madrid', 40.4168, -3.7038),
('Oak Park', 41.8850, -87.7845),
('Porbandar', 21.6417, 69.6293),
('Praga', 50.0755, 14.4378),
('Salzburgo', 47.8095, 13.0550),
('Stratford-upon-Avon', 52.1917, -1.7083),
('Lisboa', 38.7223, -9.1393),
('Palos de la Frontera', 37.2258, -6.8933),
('San Salvador (Bahamas)', 24.0223, -74.5354),
('Barcelona', 41.3874, 2.1686),
('Valladolid', 41.6523, -4.7245),
('Varsovia', 52.2297, 21.0122),
('París', 48.8566, 2.3522),
('Estocolmo', 59.3293, 18.0686),
('Nueva York', 40.7128, -74.0060),
('Vinci', 43.7833, 10.9167),
('Florencia', 43.7696, 11.2558),
('Milán', 45.4642, 9.1900),
('Roma', 41.9028, 12.4964),
('Amboise', 47.4133, 0.9836),
('Ajaccio', 41.9192, 8.7386),
('Alcalá de Henares', 40.4818, -3.3635),
('Alejandría', 31.2001, 29.9187),
('Alesia', 47.5386, 4.5000),
('Argel', 36.7538, 3.0588),
('Arlés', 43.6761, 4.6306),
('Atchison', 39.5636, -95.1174),
('Atenas', 37.9838, 23.7275),
('Atlanta', 33.7490, -84.3880),
('Auvers-sur-Oise', 49.0700, 2.1700),
('Babilonia', 32.5420, 44.4200),
('Barranquilla', 10.9685, -74.7813),
('Bath', 51.3811, -2.3590),
('Berlín', 52.5200, 13.4050),
('Berna', 46.9480, 7.4474),
('Blenheim', 51.8414, -1.3612),
('Bogotá', 4.7110, -74.0721),
('Bolonia', 44.4949, 11.3426),
('Bonn', 50.7374, 7.0982),
('Bruselas', 50.8503, 4.3517),
('Calcis', 38.4636, 23.5930),
('Cambridge', 52.2053, 0.1218),
('Caprese', 43.6910, 11.9350),
('Caracas', 10.4806, -66.9036),
('Chawton', 51.0990, -0.9830),
('Ciudad del Cabo', -33.9249, 18.4241),
('Ciudad de México', 19.4326, -99.1332),
('Colorado Springs', 38.8339, -104.8214),
('Dandi', 21.0200, 72.7500),
('Delio', 38.4000, 23.7500),
('Dole', 47.0928, 5.4897),
('Domrémy', 48.2000, 5.6800),
('Downe', 51.3309, 0.0530),
('Eisenach', 50.9800, 10.3200),
('Estagira', 40.5160, 23.6850),
('Figueras', 42.2662, 2.9622),
('Filipinas (Mactán)', 10.3100, 123.9800),
('Florida (Misuri)', 39.6989, -91.9887),
('Frombork', 54.3600, 19.6700),
('Gads Hill Place', 51.4000, 0.4800),
('Gaugamela', 36.3500, 43.2500),
('Gettysburg', 39.8309, -77.2311),
('Guanajuato', 21.0190, -101.2574),
('Hannibal', 39.7085, -91.3585),
('Hartford', 41.7658, -72.6734),
('Hodgenville', 37.5734, -85.7391),
('Isla Howland', 0.8047, -176.6169),
('Isla Negra', -33.4000, -71.6500),
('Islas Galápagos', -0.9538, -90.9656),
('Johannesburgo', -26.2041, 28.0473),
('Ketchum', 43.6805, -114.3637),
('La Habana', 23.1136, -82.3666),
('La Haya', 52.0705, 4.3007),
('Leipzig', 51.3397, 12.3731),
('Lepanto', 38.3937, 21.8288),
('Lille', 50.6292, 3.0573),
('Lima', -12.0464, -77.0428),
('Lochfield', 55.6100, -4.3000),
('Londres', 51.5072, -0.1276),
('Los Ángeles', 34.0522, -118.2437),
('Málaga', 36.7213, -4.4214),
('Marnes-la-Coquette', 48.8333, 2.1667),
('Memphis', 35.1495, -90.0490),
('Menlo Park', 40.4093, -74.4229),
('Milan (Ohio)', 41.2984, -82.6046),
('Montgomery', 32.3792, -86.3077),
('Mougins', 43.6008, 6.9989),
('Mvezo', -31.8900, 28.6000),
('Nueva Delhi', 28.6139, 77.2090),
('Orleans', 47.9029, 1.9093),
('Oxford', 51.7520, -1.2577),
('Padua', 45.4064, 11.8768),
('Parral', -36.1667, -71.8333),
('Pekín', 39.9042, 116.4074),
('Pella', 40.7620, 22.5300),
('Pisa', 43.7228, 10.4017),
('Portsmouth', 50.8198, -1.0880),
('Potidea', 40.2500, 23.3000),
('Princeton', 40.3573, -74.6672),
('Příbor', 49.6390, 18.1440),
('Queronea', 38.4900, 22.8400),
('Redding', 41.3037, -73.3579),
('Reims', 49.2583, 4.0317),
('Robben Island', -33.8070, 18.3660),
('Rodmell', 50.8730, 0.0290),
('Ruan', 49.4431, 1.0993),
('Sabrosa', 41.2590, -7.5670),
('Sanlúcar de Barrameda', 36.7784, -6.3530),
('Santa Elena', -15.9650, -5.7089),
('Santa Marta', 11.2408, -74.1990),
('Santiago de Chile', -33.4489, -70.6693),
('Sevilla', 37.3891, -5.9845),
('Shrewsbury', 52.7069, -2.7527),
('Siracusa', 37.0755, 15.2866),
('Smiljan', 44.4780, 15.3250),
('Springfield (Illinois)', 39.7817, -89.6501),
('Steventon', 51.2190, -1.2070),
('Toruń', 53.0138, 18.5981),
('Tolón', 43.1242, 5.9280),
('Tréveris', 49.7596, 6.6441),
('Ulm', 48.4011, 9.9876),
('Valldemossa', 39.7092, 2.6225),
('Venecia', 45.4408, 12.3155),
('Versalles', 48.8049, 2.1204),
('Viena', 48.2082, 16.3738),
('Waterloo', 50.7167, 4.4000),
('Washington D.C.', 38.9072, -77.0369),
('Weimar', 50.9795, 11.3235),
('West Orange', 40.7987, -74.2391),
('Winchester', 51.0632, -1.3080),
('Woolsthorpe', 52.8180, -0.6070),
('Zundert', 51.4667, 4.6500);

insert into personajes (nombre, nombres_alternativos) values
('Cristóbal Colón', array['Colón','Cristobal Colon','Christopher Columbus','Cristoforo Colombo']),
('Marie Curie', array['Marie Curie','Maria Sklodowska','Marie Sklodowska-Curie','Madame Curie']),
('Leonardo da Vinci', array['Leonardo','Da Vinci','Leonardo Da Vinci']),
('Wolfgang Amadeus Mozart', array['Mozart','Wolfgang Mozart','Amadeus Mozart']),
('Ludwig van Beethoven', array['Beethoven','Ludwig Beethoven']),
('Johann Sebastian Bach', array['Bach','J.S. Bach','Juan Sebastian Bach']),
('Frédéric Chopin', array['Chopin','Fryderyk Chopin','Federico Chopin']),
('Pablo Picasso', array['Picasso','Pablo Ruiz Picasso']),
('Vincent van Gogh', array['Van Gogh','Vincent Van Gogh']),
('Salvador Dalí', array['Dali','Salvador Dali']),
('Frida Kahlo', array['Frida','Kahlo']),
('Diego Rivera', array['Rivera','Diego Rivera']),
('Miguel Ángel Buonarroti', array['Miguel Angel','Michelangelo','Michelangelo Buonarroti']),
('Amelia Earhart', array['Earhart']),
('William Shakespeare', array['Shakespeare','Guillermo Shakespeare']),
('Miguel de Cervantes', array['Cervantes','Miguel de Cervantes Saavedra']),
('Ernest Hemingway', array['Hemingway']),
('Mark Twain', array['Twain','Samuel Clemens','Samuel Langhorne Clemens']),
('Jane Austen', array['Austen']),
('Charles Dickens', array['Dickens']),
('Virginia Woolf', array['Woolf']),
('Gabriel García Márquez', array['Garcia Marquez','Gabo','Gabriel Garcia Marquez']),
('Pablo Neruda', array['Neruda']),
('Isaac Newton', array['Newton','Sir Isaac Newton']),
('Albert Einstein', array['Einstein']),
('Charles Darwin', array['Darwin']),
('Nikola Tesla', array['Tesla']),
('Thomas Edison', array['Edison','Thomas Alva Edison']),
('Galileo Galilei', array['Galileo','Galileo Galilei']),
('Nicolás Copérnico', array['Copernico','Nicolas Copernico','Nicolaus Copernicus']),
('Alexander Fleming', array['Fleming','Alexander Flemming']),
('Louis Pasteur', array['Pasteur']),
('Stephen Hawking', array['Hawking']),
('Sigmund Freud', array['Freud']),
('Karl Marx', array['Marx']),
('Ada Lovelace', array['Lovelace','Ada Byron']),
('Sócrates', array['Socrates']),
('Platón', array['Platon','Plato']),
('Aristóteles', array['Aristoteles','Aristotle']),
('Marie Antoinette', array['Maria Antonieta','Marie-Antoinette']),
('Julio César', array['Julio Cesar','Julius Caesar','Cayo Julio Cesar']),
('Cleopatra', array['Cleopatra VII']),
('Alejandro Magno', array['Alexander the Great','Alejandro III de Macedonia','Alejandro Magno de Macedonia']),
('Juana de Arco', array['Joan of Arc','Jeanne d''Arc']),
('Napoleón Bonaparte', array['Napoleon','Napoleon Bonaparte','Napoleon I']),
('Simón Bolívar', array['Simon Bolivar','El Libertador']),
('Mahatma Gandhi', array['Gandhi','Mohandas Gandhi','Mahatma Ghandi']),
('Nelson Mandela', array['Mandela']),
('Martin Luther King', array['Martin Luther King Jr.','MLK']),
('Abraham Lincoln', array['Lincoln']),
('Winston Churchill', array['Churchill']),
('Marco Polo', array['Polo']),
('Fernando de Magallanes', array['Magallanes','Ferdinand Magellan','Fernao de Magalhaes']);

insert into hechos (personaje_id, ciudad_id, anio, actividad, orden, palabra_clave)
select p.id, c.id, v.anio, v.actividad, v.orden, v.palabra_clave
from (values
  ('Cristóbal Colón', 'Génova', 1451, 'Nace en el seno de una familia de tejedores', 1, 'Nacimiento'),
  ('Cristóbal Colón', 'Lisboa', 1477, 'Se instala y aprende náutica y cartografía', 2, 'Formación'),
  ('Cristóbal Colón', 'Palos de la Frontera', 1492, 'Zarpa hacia las Indias con la Niña, la Pinta y la Santa María', 3, 'Zarpa'),
  ('Cristóbal Colón', 'San Salvador (Bahamas)', 1492, 'Llega a tierra tras cruzar el Atlántico', 4, 'Llegada'),
  ('Cristóbal Colón', 'Barcelona', 1493, 'Es recibido por los Reyes Católicos tras su primer viaje', 5, 'Recibimiento'),
  ('Cristóbal Colón', 'Valladolid', 1506, 'Muere sin saber que había llegado a un nuevo continente', 6, 'Muerte'),
  ('Marie Curie', 'Varsovia', 1867, 'Nace y crece en la Polonia bajo dominio ruso', 1, 'Nacimiento'),
  ('Marie Curie', 'París', 1891, 'Se traslada a estudiar Física y Matemáticas en la Sorbona', 2, 'Estudios'),
  ('Marie Curie', 'Estocolmo', 1903, 'Recibe el Premio Nobel de Física junto a Pierre Curie y Henri Becquerel', 3, 'Nobel'),
  ('Marie Curie', 'Nueva York', 1921, 'Realiza una gira por Estados Unidos y recibe un gramo de radio', 4, 'Gira'),
  ('Marie Curie', 'París', 1934, 'Muere en Passy a causa de una anemia aplásica', 5, 'Muerte'),
  ('Leonardo da Vinci', 'Vinci', 1452, 'Nace cerca de Florencia, hijo de un notario', 1, 'Nacimiento'),
  ('Leonardo da Vinci', 'Florencia', 1466, 'Entra como aprendiz en el taller de Verrocchio', 2, 'Aprendizaje'),
  ('Leonardo da Vinci', 'Milán', 1482, 'Se pone al servicio de Ludovico Sforza y pinta "La Última Cena"', 3, 'Pintura'),
  ('Leonardo da Vinci', 'Roma', 1513, 'Trabaja para la familia Médici en el Vaticano', 4, 'Vaticano'),
  ('Leonardo da Vinci', 'Amboise', 1516, 'Se traslada a Francia invitado por el rey Francisco I', 5, 'Traslado'),
  ('Leonardo da Vinci', 'Amboise', 1519, 'Muere en el castillo de Cloux, cerca de Amboise', 6, 'Muerte'),
  ('Wolfgang Amadeus Mozart', 'Salzburgo', 1756, 'Nace mostrando un talento musical precoz desde niño', 1, 'Nacimiento'),
  ('Wolfgang Amadeus Mozart', 'Viena', 1781, 'Se instala en la ciudad como compositor independiente', 2, 'Instalación'),
  ('Wolfgang Amadeus Mozart', 'Praga', 1787, 'Estrena con gran éxito la ópera "Don Giovanni"', 3, 'Estreno'),
  ('Wolfgang Amadeus Mozart', 'Viena', 1791, 'Muere joven dejando inacabado su "Requiem"', 4, 'Muerte'),
  ('Ludwig van Beethoven', 'Bonn', 1770, 'Nace en una familia de músicos al servicio de la corte', 1, 'Nacimiento'),
  ('Ludwig van Beethoven', 'Viena', 1792, 'Se traslada a la ciudad para estudiar con Joseph Haydn', 2, 'Estudios'),
  ('Ludwig van Beethoven', 'Viena', 1808, 'Estrena su Quinta Sinfonía pese a ir perdiendo el oído', 3, 'Estreno'),
  ('Ludwig van Beethoven', 'Viena', 1827, 'Muere en la ciudad ya completamente sordo', 4, 'Muerte'),
  ('Johann Sebastian Bach', 'Eisenach', 1685, 'Nace en una extensa familia de músicos alemanes', 1, 'Nacimiento'),
  ('Johann Sebastian Bach', 'Weimar', 1708, 'Trabaja como organista y compositor de la corte', 2, 'Organista'),
  ('Johann Sebastian Bach', 'Leipzig', 1723, 'Se convierte en cantor de la iglesia de Santo Tomás', 3, 'Cantor'),
  ('Johann Sebastian Bach', 'Leipzig', 1750, 'Muere tras dejar una obra musical inmensa', 4, 'Muerte'),
  ('Frédéric Chopin', 'Varsovia', 1810, 'Nace y muestra un talento precoz para el piano', 1, 'Nacimiento'),
  ('Frédéric Chopin', 'Varsovia', 1830, 'Abandona Polonia tras el estallido de una revuelta contra Rusia', 2, 'Exilio'),
  ('Frédéric Chopin', 'París', 1832, 'Se instala en la ciudad como pianista y compositor de referencia', 3, 'Instalación'),
  ('Frédéric Chopin', 'Valldemossa', 1838, 'Pasa un invierno buscando mejorar su salud junto a George Sand', 4, 'Invierno'),
  ('Frédéric Chopin', 'París', 1849, 'Muere en la ciudad a causa de la tuberculosis', 5, 'Muerte'),
  ('Pablo Picasso', 'Málaga', 1881, 'Nace y comienza a dibujar desde niño', 1, 'Nacimiento'),
  ('Pablo Picasso', 'Barcelona', 1900, 'Se traslada con su familia y frecuenta ambientes artísticos bohemios', 2, 'Bohemia'),
  ('Pablo Picasso', 'París', 1907, 'Pinta "Las señoritas de Avignon", germen del cubismo', 3, 'Cubismo'),
  ('Pablo Picasso', 'París', 1937, 'Pinta el "Guernica" en respuesta al bombardeo de la localidad vasca', 4, 'Guernica'),
  ('Pablo Picasso', 'Mougins', 1973, 'Muere en su residencia del sur de Francia', 5, 'Muerte'),
  ('Vincent van Gogh', 'Zundert', 1853, 'Nace hijo de un pastor protestante', 1, 'Nacimiento'),
  ('Vincent van Gogh', 'La Haya', 1881, 'Comienza a dedicarse en serio a la pintura', 2, 'Pintura'),
  ('Vincent van Gogh', 'Arlés', 1888, 'Pinta algunas de sus obras más conocidas, como "Los Girasoles"', 3, 'Pintura'),
  ('Vincent van Gogh', 'Auvers-sur-Oise', 1890, 'Muere sin haber vendido apenas cuadros en vida', 4, 'Muerte'),
  ('Salvador Dalí', 'Figueras', 1904, 'Nace en el seno de una familia acomodada catalana', 1, 'Nacimiento'),
  ('Salvador Dalí', 'Madrid', 1922, 'Estudia en la Residencia de Estudiantes junto a Lorca y Buñuel', 2, 'Estudios'),
  ('Salvador Dalí', 'París', 1929, 'Se une al movimiento surrealista', 3, 'Surrealismo'),
  ('Salvador Dalí', 'Nueva York', 1939, 'Expone y se hace célebre en Estados Unidos', 4, 'Exposición'),
  ('Salvador Dalí', 'Figueras', 1989, 'Muere en su ciudad natal', 5, 'Muerte'),
  ('Frida Kahlo', 'Ciudad de México', 1907, 'Nace en la Casa Azul de su familia', 1, 'Nacimiento'),
  ('Frida Kahlo', 'Ciudad de México', 1925, 'Sufre un grave accidente de autobús que marcará su vida y su obra', 2, 'Accidente'),
  ('Frida Kahlo', 'Ciudad de México', 1929, 'Se casa con el muralista Diego Rivera', 3, 'Boda'),
  ('Frida Kahlo', 'Nueva York', 1938, 'Expone su obra con gran éxito de crítica', 4, 'Exposición'),
  ('Frida Kahlo', 'Ciudad de México', 1954, 'Muere en la misma casa donde nació', 5, 'Muerte'),
  ('Diego Rivera', 'Guanajuato', 1886, 'Nace en una familia de clase media mexicana', 1, 'Nacimiento'),
  ('Diego Rivera', 'París', 1909, 'Vive y pinta influido por el cubismo europeo', 2, 'Cubismo'),
  ('Diego Rivera', 'Ciudad de México', 1933, 'Pinta murales sobre la historia y la revolución mexicana', 3, 'Murales'),
  ('Diego Rivera', 'Ciudad de México', 1957, 'Muere tras una vida dedicada al muralismo', 4, 'Muerte'),
  ('Miguel Ángel Buonarroti', 'Caprese', 1475, 'Nace en una pequeña localidad de la Toscana', 1, 'Nacimiento'),
  ('Miguel Ángel Buonarroti', 'Florencia', 1490, 'Se forma en el taller de Ghirlandaio y en el entorno de los Médici', 2, 'Aprendizaje'),
  ('Miguel Ángel Buonarroti', 'Roma', 1508, 'Pinta el techo de la Capilla Sixtina', 3, 'Capilla'),
  ('Miguel Ángel Buonarroti', 'Roma', 1564, 'Muere tras una vida dedicada a la escultura, la pintura y la arquitectura', 4, 'Muerte'),
  ('Amelia Earhart', 'Atchison', 1897, 'Nace en una familia de clase media estadounidense', 1, 'Nacimiento'),
  ('Amelia Earhart', 'Los Ángeles', 1921, 'Aprende a volar y compra su primer avión', 2, 'Vuelo'),
  ('Amelia Earhart', 'París', 1932, 'Se convierte en la primera mujer en cruzar el Atlántico en solitario', 3, 'Travesía'),
  ('Amelia Earhart', 'Isla Howland', 1937, 'Desaparece durante un intento de dar la vuelta al mundo', 4, 'Desaparición'),
  ('William Shakespeare', 'Stratford-upon-Avon', 1564, 'Nace en una familia de comerciantes', 1, 'Nacimiento'),
  ('William Shakespeare', 'Londres', 1592, 'Triunfa como dramaturgo y actor en los teatros de la ciudad', 2, 'Teatro'),
  ('William Shakespeare', 'Londres', 1599, 'Estrena obras en el recién construido Teatro Globe', 3, 'Globe'),
  ('William Shakespeare', 'Stratford-upon-Avon', 1616, 'Muere en su ciudad natal tras retirarse de los escenarios', 4, 'Muerte'),
  ('Miguel de Cervantes', 'Alcalá de Henares', 1547, 'Nace en una familia de escasos recursos', 1, 'Nacimiento'),
  ('Miguel de Cervantes', 'Lepanto', 1571, 'Participa en la batalla naval y pierde el uso de una mano', 2, 'Batalla'),
  ('Miguel de Cervantes', 'Argel', 1575, 'Es capturado por piratas berberiscos y permanece cautivo varios años', 3, 'Cautiverio'),
  ('Miguel de Cervantes', 'Madrid', 1605, 'Publica la primera parte de "Don Quijote de la Mancha"', 4, 'Quijote'),
  ('Miguel de Cervantes', 'Madrid', 1616, 'Muere en la pobreza pese al éxito de su obra', 5, 'Muerte'),
  ('Ernest Hemingway', 'Oak Park', 1899, 'Nace en una familia acomodada de un suburbio de Chicago', 1, 'Nacimiento'),
  ('Ernest Hemingway', 'Milán', 1918, 'Es herido como voluntario de ambulancias en la Primera Guerra Mundial', 2, 'Guerra'),
  ('Ernest Hemingway', 'París', 1921, 'Vive como parte de la "generación perdida" de escritores estadounidenses', 3, 'Bohemia'),
  ('Ernest Hemingway', 'La Habana', 1939, 'Se instala y escribe algunas de sus obras más conocidas', 4, 'Instalación'),
  ('Ernest Hemingway', 'Ketchum', 1961, 'Muere en su casa de Idaho', 5, 'Muerte'),
  ('Mark Twain', 'Florida (Misuri)', 1835, 'Nace en un pequeño pueblo de Misuri', 1, 'Nacimiento'),
  ('Mark Twain', 'Hannibal', 1857, 'Trabaja como piloto de barcos de vapor en el Misisipi, experiencia que marcará su obra', 2, 'Navegación'),
  ('Mark Twain', 'Hartford', 1876, 'Publica "Las aventuras de Tom Sawyer"', 3, 'Publicación'),
  ('Mark Twain', 'Redding', 1910, 'Muere en su casa de Connecticut', 4, 'Muerte'),
  ('Jane Austen', 'Steventon', 1775, 'Nace hija de un pastor rural inglés', 1, 'Nacimiento'),
  ('Jane Austen', 'Bath', 1801, 'Se traslada con su familia a esta ciudad balneario', 2, 'Traslado'),
  ('Jane Austen', 'Chawton', 1811, 'Publica de forma anónima "Sentido y sensibilidad"', 3, 'Publicación'),
  ('Jane Austen', 'Winchester', 1817, 'Muere sin haber visto reconocido públicamente su nombre como autora', 4, 'Muerte'),
  ('Charles Dickens', 'Portsmouth', 1812, 'Nace hijo de un empleado de la marina', 1, 'Nacimiento'),
  ('Charles Dickens', 'Londres', 1836, 'Publica "Los papeles póstumos del Club Pickwick" y alcanza gran popularidad', 2, 'Popularidad'),
  ('Charles Dickens', 'Londres', 1843, 'Publica "Cuento de Navidad"', 3, 'Publicación'),
  ('Charles Dickens', 'Gads Hill Place', 1870, 'Muere en su residencia de Kent', 4, 'Muerte'),
  ('Virginia Woolf', 'Londres', 1882, 'Nace en una familia culta de la época victoriana', 1, 'Nacimiento'),
  ('Virginia Woolf', 'Londres', 1912, 'Se casa con Leonard Woolf y forma parte del círculo de Bloomsbury', 2, 'Boda'),
  ('Virginia Woolf', 'Londres', 1925, 'Publica "La señora Dalloway"', 3, 'Publicación'),
  ('Virginia Woolf', 'Rodmell', 1941, 'Muere ahogada en el río Ouse cerca de su casa', 4, 'Muerte'),
  ('Gabriel García Márquez', 'Aracataca', 1927, 'Nace en un pequeño pueblo de la costa caribeña colombiana', 1, 'Nacimiento'),
  ('Gabriel García Márquez', 'Barranquilla', 1950, 'Trabaja como periodista y comienza a escribir sus primeros relatos', 2, 'Periodismo'),
  ('Gabriel García Márquez', 'Ciudad de México', 1967, 'Publica "Cien años de soledad"', 3, 'Publicación'),
  ('Gabriel García Márquez', 'Estocolmo', 1982, 'Recibe el Premio Nobel de Literatura', 4, 'Nobel'),
  ('Gabriel García Márquez', 'Ciudad de México', 2014, 'Muere en su casa de México', 5, 'Muerte'),
  ('Pablo Neruda', 'Parral', 1904, 'Nace en el sur de Chile', 1, 'Nacimiento'),
  ('Pablo Neruda', 'Santiago de Chile', 1923, 'Publica "Veinte poemas de amor y una canción desesperada"', 2, 'Publicación'),
  ('Pablo Neruda', 'Madrid', 1935, 'Vive como diplomático chileno durante los años previos a la Guerra Civil española', 3, 'Diplomacia'),
  ('Pablo Neruda', 'Estocolmo', 1971, 'Recibe el Premio Nobel de Literatura', 4, 'Nobel'),
  ('Pablo Neruda', 'Isla Negra', 1973, 'Muere pocos días después del golpe de Estado en Chile', 5, 'Muerte'),
  ('Isaac Newton', 'Woolsthorpe', 1643, 'Nace de forma prematura tras la muerte de su padre', 1, 'Nacimiento'),
  ('Isaac Newton', 'Cambridge', 1665, 'Desarrolla parte de sus teorías sobre la gravedad durante una epidemia de peste', 2, 'Gravedad'),
  ('Isaac Newton', 'Londres', 1687, 'Publica los "Principia Mathematica"', 3, 'Publicación'),
  ('Isaac Newton', 'Londres', 1727, 'Muere tras dirigir durante años la Casa de la Moneda británica', 4, 'Muerte'),
  ('Albert Einstein', 'Ulm', 1879, 'Nace en una familia judía alemana', 1, 'Nacimiento'),
  ('Albert Einstein', 'Berna', 1905, 'Publica varios artículos revolucionarios, entre ellos la teoría de la relatividad especial', 2, 'Relatividad'),
  ('Albert Einstein', 'Berlín', 1915, 'Presenta la teoría de la relatividad general', 3, 'Relatividad'),
  ('Albert Einstein', 'Princeton', 1955, 'Muere tras años dedicado a la física teórica en Estados Unidos', 4, 'Muerte'),
  ('Charles Darwin', 'Shrewsbury', 1809, 'Nace en una familia acomodada inglesa', 1, 'Nacimiento'),
  ('Charles Darwin', 'Islas Galápagos', 1835, 'Observa la fauna que inspirará su teoría de la evolución', 2, 'Evolución'),
  ('Charles Darwin', 'Londres', 1859, 'Publica "El origen de las especies"', 3, 'Publicación'),
  ('Charles Darwin', 'Downe', 1882, 'Muere en su casa de campo tras décadas de investigación', 4, 'Muerte'),
  ('Nikola Tesla', 'Smiljan', 1856, 'Nace en el seno de una familia serbia', 1, 'Nacimiento'),
  ('Nikola Tesla', 'Nueva York', 1884, 'Emigra a Estados Unidos y trabaja brevemente con Thomas Edison', 2, 'Emigración'),
  ('Nikola Tesla', 'Colorado Springs', 1899, 'Realiza experimentos con corriente eléctrica de alta frecuencia', 3, 'Experimentos'),
  ('Nikola Tesla', 'Nueva York', 1943, 'Muere solo en una habitación de hotel', 4, 'Muerte'),
  ('Thomas Edison', 'Milan (Ohio)', 1847, 'Nace en un pequeño pueblo de Ohio', 1, 'Nacimiento'),
  ('Thomas Edison', 'Menlo Park', 1879, 'Desarrolla la primera bombilla incandescente comercialmente viable', 2, 'Bombilla'),
  ('Thomas Edison', 'Nueva York', 1882, 'Pone en marcha la primera central eléctrica comercial del mundo', 3, 'Electricidad'),
  ('Thomas Edison', 'West Orange', 1931, 'Muere tras registrar más de mil patentes', 4, 'Muerte'),
  ('Galileo Galilei', 'Pisa', 1564, 'Nace en una familia de músicos y comerciantes', 1, 'Nacimiento'),
  ('Galileo Galilei', 'Padua', 1609, 'Mejora el telescopio y descubre las lunas de Júpiter', 2, 'Telescopio'),
  ('Galileo Galilei', 'Roma', 1633, 'Es juzgado por la Inquisición por defender el heliocentrismo', 3, 'Juicio'),
  ('Galileo Galilei', 'Florencia', 1642, 'Muere bajo arresto domiciliario', 4, 'Muerte'),
  ('Nicolás Copérnico', 'Toruń', 1473, 'Nace en una familia de comerciantes polacos', 1, 'Nacimiento'),
  ('Nicolás Copérnico', 'Bolonia', 1496, 'Estudia astronomía, derecho y medicina en Italia', 2, 'Estudios'),
  ('Nicolás Copérnico', 'Frombork', 1510, 'Se instala como canónigo y desarrolla sus observaciones astronómicas', 3, 'Observaciones'),
  ('Nicolás Copérnico', 'Frombork', 1543, 'Muere poco después de publicar su obra sobre el heliocentrismo', 4, 'Muerte'),
  ('Alexander Fleming', 'Lochfield', 1881, 'Nace en una granja escocesa', 1, 'Nacimiento'),
  ('Alexander Fleming', 'Londres', 1906, 'Se forma como médico y bacteriólogo', 2, 'Formación'),
  ('Alexander Fleming', 'Londres', 1928, 'Descubre por accidente la penicilina en su laboratorio', 3, 'Penicilina'),
  ('Alexander Fleming', 'Londres', 1955, 'Muere tras revolucionar la medicina con los antibióticos', 4, 'Muerte'),
  ('Louis Pasteur', 'Dole', 1822, 'Nace en una familia de curtidores franceses', 1, 'Nacimiento'),
  ('Louis Pasteur', 'Lille', 1856, 'Investiga la fermentación y desarrolla el proceso de pasteurización', 2, 'Pasteurización'),
  ('Louis Pasteur', 'París', 1885, 'Aplica con éxito la primera vacuna contra la rabia en un ser humano', 3, 'Vacuna'),
  ('Louis Pasteur', 'Marnes-la-Coquette', 1895, 'Muere cerca de París tras fundar el instituto que lleva su nombre', 4, 'Muerte'),
  ('Stephen Hawking', 'Oxford', 1942, 'Nace durante la Segunda Guerra Mundial', 1, 'Nacimiento'),
  ('Stephen Hawking', 'Cambridge', 1963, 'Es diagnosticado con una enfermedad degenerativa que le da pocos años de vida', 2, 'Diagnóstico'),
  ('Stephen Hawking', 'Cambridge', 1988, 'Publica "Breve historia del tiempo"', 3, 'Publicación'),
  ('Stephen Hawking', 'Cambridge', 2018, 'Muere tras décadas investigando los agujeros negros', 4, 'Muerte'),
  ('Sigmund Freud', 'Příbor', 1856, 'Nace en una pequeña ciudad de Moravia', 1, 'Nacimiento'),
  ('Sigmund Freud', 'Viena', 1886, 'Abre su consulta y comienza a desarrollar el psicoanálisis', 2, 'Psicoanálisis'),
  ('Sigmund Freud', 'Viena', 1900, 'Publica "La interpretación de los sueños"', 3, 'Publicación'),
  ('Sigmund Freud', 'Londres', 1939, 'Muere en el exilio tras huir del nazismo', 4, 'Exilio'),
  ('Karl Marx', 'Tréveris', 1818, 'Nace en una familia de abogados alemanes', 1, 'Nacimiento'),
  ('Karl Marx', 'París', 1844, 'Traba amistad con Friedrich Engels y desarrolla sus ideas económicas', 2, 'Amistad'),
  ('Karl Marx', 'Bruselas', 1848, 'Publica junto a Engels "El manifiesto comunista"', 3, 'Manifiesto'),
  ('Karl Marx', 'Londres', 1883, 'Muere en el exilio tras dedicar años a escribir "El Capital"', 4, 'Muerte'),
  ('Ada Lovelace', 'Londres', 1815, 'Nace hija del poeta Lord Byron', 1, 'Nacimiento'),
  ('Ada Lovelace', 'Londres', 1835, 'Se casa con William King, conde de Lovelace', 2, 'Boda'),
  ('Ada Lovelace', 'Londres', 1843, 'Publica notas sobre la máquina analítica de Babbage consideradas el primer algoritmo informático', 3, 'Algoritmo'),
  ('Ada Lovelace', 'Londres', 1852, 'Muere joven a causa de un cáncer', 4, 'Muerte'),
  ('Sócrates', 'Atenas', -470, 'Nace en el seno de una familia humilde ateniense', 1, 'Nacimiento'),
  ('Sócrates', 'Potidea', -432, 'Participa como hoplita en el asedio de Potidea', 2, 'Batalla'),
  ('Sócrates', 'Delio', -424, 'Combate en la batalla de Delio durante la Guerra del Peloponeso', 3, 'Batalla'),
  ('Sócrates', 'Atenas', -399, 'Es condenado a muerte y muere bebiendo cicuta', 4, 'Condena'),
  ('Platón', 'Atenas', -428, 'Nace en una familia aristocrática ateniense', 1, 'Nacimiento'),
  ('Platón', 'Atenas', -387, 'Funda la Academia, una de las primeras instituciones de enseñanza superior', 2, 'Academia'),
  ('Platón', 'Siracusa', -367, 'Viaja a Sicilia para intentar formar a un gobernante filósofo', 3, 'Viaje'),
  ('Platón', 'Atenas', -348, 'Muere en su ciudad natal', 4, 'Muerte'),
  ('Aristóteles', 'Estagira', -384, 'Nace en una ciudad griega del norte', 1, 'Nacimiento'),
  ('Aristóteles', 'Atenas', -367, 'Se traslada para estudiar en la Academia de Platón', 2, 'Estudios'),
  ('Aristóteles', 'Pella', -343, 'Es tutor del joven Alejandro Magno en la corte macedonia', 3, 'Tutoría'),
  ('Aristóteles', 'Atenas', -335, 'Funda su propia escuela, el Liceo', 4, 'Liceo'),
  ('Aristóteles', 'Calcis', -322, 'Muere en el exilio tras la muerte de Alejandro Magno', 5, 'Muerte'),
  ('Marie Antoinette', 'Viena', 1755, 'Nace como archiduquesa de Austria', 1, 'Nacimiento'),
  ('Marie Antoinette', 'Versalles', 1770, 'Se casa con el futuro Luis XVI de Francia', 2, 'Boda'),
  ('Marie Antoinette', 'Versalles', 1789, 'Vive el estallido de la Revolución Francesa', 3, 'Revolución'),
  ('Marie Antoinette', 'París', 1793, 'Muere guillotinada durante el Terror revolucionario', 4, 'Guillotina'),
  ('Julio César', 'Roma', -100, 'Nace en una familia patricia romana', 1, 'Nacimiento'),
  ('Julio César', 'Alesia', -52, 'Vence a Vercingétorix tras el asedio que sella la conquista de la Galia', 2, 'Conquista'),
  ('Julio César', 'Roma', -49, 'Cruza el Rubicón e inicia una guerra civil', 3, 'Rubicón'),
  ('Julio César', 'Roma', -44, 'Muere asesinado por senadores el día de los Idus de marzo', 4, 'Asesinato'),
  ('Cleopatra', 'Alejandría', -69, 'Nace en la dinastía ptolemaica de Egipto', 1, 'Nacimiento'),
  ('Cleopatra', 'Alejandría', -48, 'Se convierte en aliada y compañera de Julio César', 2, 'Alianza'),
  ('Cleopatra', 'Actium', -31, 'Es derrotada junto a Marco Antonio en la batalla naval de Actium', 3, 'Batalla'),
  ('Cleopatra', 'Alejandría', -30, 'Muere tras la conquista romana de Egipto', 4, 'Muerte'),
  ('Alejandro Magno', 'Pella', -356, 'Nace heredero del trono de Macedonia', 1, 'Nacimiento'),
  ('Alejandro Magno', 'Queronea', -338, 'Combate de forma decisiva junto a su padre Filipo II', 2, 'Batalla'),
  ('Alejandro Magno', 'Gaugamela', -331, 'Derrota al imperio persa de Darío III', 3, 'Batalla'),
  ('Alejandro Magno', 'Babilonia', -323, 'Muere joven en la ciudad que había hecho capital de su imperio', 4, 'Muerte'),
  ('Juana de Arco', 'Domrémy', 1412, 'Nace en una familia campesina de Lorena', 1, 'Nacimiento'),
  ('Juana de Arco', 'Orleans', 1429, 'Libera la ciudad del asedio inglés', 2, 'Liberación'),
  ('Juana de Arco', 'Reims', 1429, 'Acompaña la coronación de Carlos VII como rey de Francia', 3, 'Coronación'),
  ('Juana de Arco', 'Ruan', 1431, 'Muere en la hoguera acusada de herejía', 4, 'Hoguera'),
  ('Napoleón Bonaparte', 'Ajaccio', 1769, 'Nace en una familia de la pequeña nobleza corsa', 1, 'Nacimiento'),
  ('Napoleón Bonaparte', 'Tolón', 1793, 'Se distingue militarmente durante el asedio de la ciudad', 2, 'Asedio'),
  ('Napoleón Bonaparte', 'París', 1804, 'Se corona emperador de los franceses', 3, 'Coronación'),
  ('Napoleón Bonaparte', 'Waterloo', 1815, 'Sufre su derrota militar definitiva', 4, 'Derrota'),
  ('Napoleón Bonaparte', 'Santa Elena', 1821, 'Muere en el exilio en una isla del Atlántico Sur', 5, 'Exilio'),
  ('Simón Bolívar', 'Caracas', 1783, 'Nace en una familia acomodada criolla', 1, 'Nacimiento'),
  ('Simón Bolívar', 'Bogotá', 1819, 'Libera Nueva Granada tras la batalla de Boyacá', 2, 'Independencia'),
  ('Simón Bolívar', 'Lima', 1824, 'Consuma la independencia de Perú', 3, 'Independencia'),
  ('Simón Bolívar', 'Santa Marta', 1830, 'Muere enfermo tras la fragmentación de la Gran Colombia', 4, 'Muerte'),
  ('Mahatma Gandhi', 'Porbandar', 1869, 'Nace en una familia hindú de la costa oeste de la India', 1, 'Nacimiento'),
  ('Mahatma Gandhi', 'Johannesburgo', 1893, 'Desarrolla su método de resistencia no violenta durante su etapa en Sudáfrica', 2, 'Resistencia'),
  ('Mahatma Gandhi', 'Dandi', 1930, 'Encabeza la Marcha de la Sal contra el monopolio británico', 3, 'Marcha'),
  ('Mahatma Gandhi', 'Nueva Delhi', 1948, 'Muere asesinado poco después de la independencia de la India', 4, 'Asesinato'),
  ('Nelson Mandela', 'Mvezo', 1918, 'Nace en una familia de la realeza local xhosa', 1, 'Nacimiento'),
  ('Nelson Mandela', 'Johannesburgo', 1962, 'Es arrestado tras años de lucha contra el apartheid', 2, 'Arresto'),
  ('Nelson Mandela', 'Robben Island', 1964, 'Es condenado a cadena perpetua y encarcelado en la isla', 3, 'Condena'),
  ('Nelson Mandela', 'Ciudad del Cabo', 1990, 'Es liberado tras 27 años de prisión', 4, 'Liberación'),
  ('Nelson Mandela', 'Johannesburgo', 2013, 'Muere tras convertirse en el primer presidente negro de Sudáfrica', 5, 'Muerte'),
  ('Martin Luther King', 'Atlanta', 1929, 'Nace hijo de un pastor baptista', 1, 'Nacimiento'),
  ('Martin Luther King', 'Montgomery', 1955, 'Lidera el boicot a los autobuses tras el arresto de Rosa Parks', 2, 'Boicot'),
  ('Martin Luther King', 'Washington D.C.', 1963, 'Pronuncia su discurso "I Have a Dream"', 3, 'Discurso'),
  ('Martin Luther King', 'Memphis', 1968, 'Muere asesinado en el balcón de un motel', 4, 'Asesinato'),
  ('Abraham Lincoln', 'Hodgenville', 1809, 'Nace en una cabaña de madera', 1, 'Nacimiento'),
  ('Abraham Lincoln', 'Springfield (Illinois)', 1860, 'Es elegido presidente de Estados Unidos', 2, 'Elección'),
  ('Abraham Lincoln', 'Gettysburg', 1863, 'Pronuncia su célebre discurso durante la Guerra Civil', 3, 'Discurso'),
  ('Abraham Lincoln', 'Washington D.C.', 1865, 'Muere asesinado poco después de terminar la guerra', 4, 'Asesinato'),
  ('Winston Churchill', 'Blenheim', 1874, 'Nace en el palacio familiar de los Churchill', 1, 'Nacimiento'),
  ('Winston Churchill', 'Londres', 1940, 'Se convierte en primer ministro británico al inicio de la Segunda Guerra Mundial', 2, 'Nombramiento'),
  ('Winston Churchill', 'Londres', 1945, 'Lidera al Reino Unido hasta la victoria aliada', 3, 'Victoria'),
  ('Winston Churchill', 'Londres', 1965, 'Muere tras una larga carrera política', 4, 'Muerte'),
  ('Marco Polo', 'Venecia', 1254, 'Nace en una familia de comerciantes venecianos', 1, 'Nacimiento'),
  ('Marco Polo', 'Pekín', 1275, 'Llega a la corte del emperador mongol Kublai Kan', 2, 'Corte'),
  ('Marco Polo', 'Génova', 1298, 'Es hecho prisionero y dicta el relato de sus viajes', 3, 'Cautiverio'),
  ('Marco Polo', 'Venecia', 1324, 'Muere en su ciudad natal', 4, 'Muerte'),
  ('Fernando de Magallanes', 'Sabrosa', 1480, 'Nace en una familia de la baja nobleza portuguesa', 1, 'Nacimiento'),
  ('Fernando de Magallanes', 'Sevilla', 1519, 'Zarpa al mando de una expedición para encontrar una ruta occidental a Asia', 2, 'Zarpa'),
  ('Fernando de Magallanes', 'Filipinas (Mactán)', 1521, 'Muere en un enfrentamiento con habitantes locales', 3, 'Muerte'),
  ('Fernando de Magallanes', 'Sanlúcar de Barrameda', 1522, 'Su expedición completa la primera vuelta al mundo, aunque él ya no vive para verlo', 4, 'Circunnavegación')
) as v(personaje, ciudad, anio, actividad, orden, palabra_clave)
join personajes p on p.nombre = v.personaje
join ciudades  c on c.nombre = v.ciudad;
